### ISSUE TITLE
Cannot find version on windows

### ISSUE THREAD

**Issue by amichlee** [manips-sai-org/sai2-common#7]
When calling find_package for sai2-common on Windows 10, you get this error: 

> CMake Warning at CMakeLists.txt:33 (find_package):
>   Could not find a configuration file for package "SAI2-COMMON-LITE" that is
>   compatible with requested version "".
> 
>   The following configuration files were considered but not accepted:
> 
>     C:/src/sai2-common-lite/build/SAI2-COMMON-LITEConfig.cmake, version: 0.1.0 (64bit)
> 

The current fix is to delete these portions from ConfigVersion.cmake file:

```
# if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:
if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
   return()
endif()

# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

I suspect it's because sai2-common is built in 64 bit.

**Comment by mikael-jorda** [comment]
We do not support windows for now
