### ISSUE TITLE
Sim parser can only handle 2 collision meshes per item

### ISSUE THREAD

**Issue by amichlee** [manips-sai-org/sai2-common#8]
I am using a convex decomposition of an object with several meshes for one object, but I have to manually separate the object into different items in the urdf, since the simulation parser can only handle up to 2 collision meshes per item. 

Not urgent since it's fixable with a hack, but just to keep in mind.

**Comment by mikael-jorda** [comment]
the parser in sai2-urdfreader will now only allow one collision mesh per link. We can use fixed joints for multiple collision elements
