### ISSUE TITLE
robot parsing erro

### ISSUE THREAD

**Issue by amichlee** [manips-sai-org/sai2-common#9]
Really strange parsing error. There are certain link names you can use that work (link0, link1...etc) and item, item2...

But others don't work:
item3 for example (Even though item and item2 work). 
blabla
box0
box

...

I have not investigated where the error is coming from, but you get this error in graphics: link [item3] does not exists

And in simulation, you get nan's if you don't use the right names

**Comment by shameekganguly** [comment]
I can't reproduce this:
<img width="719" alt="screen shot 2018-09-06 at 10 47 12 am" src="https://user-images.githubusercontent.com/2412842/45175432-4be6f880-b1c2-11e8-91a1-3dfc08a9f8c6.png">

Could you please attach the urdf file that failed to load?
